### ISSUE TITLE
Error Install Icon bug

### ISSUE THREAD

**Issue by rraffaelandrei** [MishaTY/Rectify11Installer#108]
### Description

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Rectify11Installer.Core.ShellLink.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at Rectify11Installer.Core.ShellLink.Save(String linkFile) in D:\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Core\ShellLink.cs:line 1027
   at Rectify11Installer.Core.Installer.FixOdbc() in D:\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Core\Installer.cs:line 344
   at Rectify11Installer.Core.Installer.<Install>b__2_29() in D:\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Core\Installer.cs:line 278
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`

### Steps To Reproduce

hi again i got an error again

### Rectify11 Version

3.0 rp3

### Windows Version

windows 11 21h2

### Logs

![Screenshot 2023-02-12 235826](https://user-images.githubusercontent.com/91460382/218402728-853b93fb-ed40-43db-a275-9241c30fc936.png)

**Comment by rraffaelandrei** [comment]
when i click continue its still say replacing files

**Comment by rounk-ctrl** [comment]
Try the latest commit

**Comment by rraffaelandrei** [comment]
i try but not work

**Comment by rraffaelandrei** [comment]
i dont see any command prompt

**Comment by rraffaelandrei** [comment]
how i can fix it?

**Comment by rraffaelandrei** [comment]
@rounk-ctrl you working on this error?

**Comment by rounk-ctrl** [comment]
It seems like a permission issue.

**Comment by rraffaelandrei** [comment]
maybe owner know? tell him

**Comment by rraffaelandrei** [comment]
i use the late update use visual studio 2022

**Comment by rraffaelandrei** [comment]
i run as adminitrator

**Comment by rraffaelandrei** [comment]
error code: 0x8007005

**Comment by rraffaelandrei** [comment]
@rounk-ctrl pls tell owner about that error maybe he know to fix

**Comment by rraffaelandrei** [comment]
some help me to fix this error 2h ago i try to fix this error and not work

**Comment by rraffaelandrei** [comment]
pls help

**Comment by fytuf** [comment]
no offense but ur very annoying, can u like stop spamming in this thread? thanks

**Comment by rraffaelandrei** [comment]
ok :(
