### ISSUE TITLE
Unhandled exception with libraryFilePath not set.

### ISSUE THREAD

**Issue by TechnoEggnog** [MishaTY/Rectify11Installer#98]
### Description

The installer shows an error popup when moving to the installing runtimes stage. The error pops up, saying there was an unhandled exception. Pressing continue makes the installer hang, and it cannot proceed. The error log mentions the SevenZipExtractor, introduced a couple commits ago.

### Steps To Reproduce

Just run the installer, go through with any settings, and start the installation process. The error message will appear immediately.

### Rectify11 Version

Commit 0ceea7

### Windows Version

Windows 11 Dev 25281

### Logs

SevenZipExtractor.SevenZipException: libraryFilePath not set
   at SevenZipExtractor.ArchiveFile.InitializeAndValidateLibrary()
   at SevenZipExtractor.ArchiveFile..ctor(String archiveFilePath, String libraryFilePath)
   at Rectify11Installer.Core.Installer.InstallRuntimes()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rectify11Installer.Core.Installer.<Install>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Rectify11Installer.frmWizard.<Navigate>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by rounk-ctrl** [comment]
Check now. I switched to SharpCompress

**Comment by rounk-ctrl** [comment]
Reverted
